// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    id, name, model, provider, persona, api_key
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, name, model, provider, persona, api_key, created_at, updated_at
`

type CreateAgentParams struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Model    string         `json:"model"`
	Provider string         `json:"provider"`
	Persona  sql.NullString `json:"persona"`
	ApiKey   sql.NullString `json:"api_key"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.queryRow(ctx, q.createAgentStmt, createAgent,
		arg.ID,
		arg.Name,
		arg.Model,
		arg.Provider,
		arg.Persona,
		arg.ApiKey,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Provider,
		&i.Persona,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteAgentStmt, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, model, provider, persona, api_key, created_at, updated_at FROM agents
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentStmt, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Provider,
		&i.Persona,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, model, provider, persona, api_key, created_at, updated_at FROM agents
ORDER BY name
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.query(ctx, q.listAgentsStmt, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Model,
			&i.Provider,
			&i.Persona,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = ?,
    model = ?,
    provider = ?,
    persona = ?,
    api_key = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, model, provider, persona, api_key, created_at, updated_at
`

type UpdateAgentParams struct {
	Name     string         `json:"name"`
	Model    string         `json:"model"`
	Provider string         `json:"provider"`
	Persona  sql.NullString `json:"persona"`
	ApiKey   sql.NullString `json:"api_key"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.queryRow(ctx, q.updateAgentStmt, updateAgent,
		arg.Name,
		arg.Model,
		arg.Provider,
		arg.Persona,
		arg.ApiKey,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Provider,
		&i.Persona,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
