// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAgentStmt, err = db.PrepareContext(ctx, createAgent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgent: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createRoomStmt, err = db.PrepareContext(ctx, createRoom); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRoom: %w", err)
	}
	if q.deleteAgentStmt, err = db.PrepareContext(ctx, deleteAgent); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAgent: %w", err)
	}
	if q.deleteRoomStmt, err = db.PrepareContext(ctx, deleteRoom); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRoom: %w", err)
	}
	if q.getAgentStmt, err = db.PrepareContext(ctx, getAgent); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgent: %w", err)
	}
	if q.getRoomStmt, err = db.PrepareContext(ctx, getRoom); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoom: %w", err)
	}
	if q.getTotalUsageStmt, err = db.PrepareContext(ctx, getTotalUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalUsage: %w", err)
	}
	if q.listAgentsStmt, err = db.PrepareContext(ctx, listAgents); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgents: %w", err)
	}
	if q.listMessagesByRoomStmt, err = db.PrepareContext(ctx, listMessagesByRoom); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesByRoom: %w", err)
	}
	if q.listRoomsStmt, err = db.PrepareContext(ctx, listRooms); err != nil {
		return nil, fmt.Errorf("error preparing query ListRooms: %w", err)
	}
	if q.listUsageLogsStmt, err = db.PrepareContext(ctx, listUsageLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsageLogs: %w", err)
	}
	if q.logUsageStmt, err = db.PrepareContext(ctx, logUsage); err != nil {
		return nil, fmt.Errorf("error preparing query LogUsage: %w", err)
	}
	if q.updateAgentStmt, err = db.PrepareContext(ctx, updateAgent); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAgent: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAgentStmt != nil {
		if cerr := q.createAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgentStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createRoomStmt != nil {
		if cerr := q.createRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRoomStmt: %w", cerr)
		}
	}
	if q.deleteAgentStmt != nil {
		if cerr := q.deleteAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAgentStmt: %w", cerr)
		}
	}
	if q.deleteRoomStmt != nil {
		if cerr := q.deleteRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRoomStmt: %w", cerr)
		}
	}
	if q.getAgentStmt != nil {
		if cerr := q.getAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentStmt: %w", cerr)
		}
	}
	if q.getRoomStmt != nil {
		if cerr := q.getRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoomStmt: %w", cerr)
		}
	}
	if q.getTotalUsageStmt != nil {
		if cerr := q.getTotalUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalUsageStmt: %w", cerr)
		}
	}
	if q.listAgentsStmt != nil {
		if cerr := q.listAgentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgentsStmt: %w", cerr)
		}
	}
	if q.listMessagesByRoomStmt != nil {
		if cerr := q.listMessagesByRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesByRoomStmt: %w", cerr)
		}
	}
	if q.listRoomsStmt != nil {
		if cerr := q.listRoomsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRoomsStmt: %w", cerr)
		}
	}
	if q.listUsageLogsStmt != nil {
		if cerr := q.listUsageLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsageLogsStmt: %w", cerr)
		}
	}
	if q.logUsageStmt != nil {
		if cerr := q.logUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing logUsageStmt: %w", cerr)
		}
	}
	if q.updateAgentStmt != nil {
		if cerr := q.updateAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAgentStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createAgentStmt        *sql.Stmt
	createMessageStmt      *sql.Stmt
	createRoomStmt         *sql.Stmt
	deleteAgentStmt        *sql.Stmt
	deleteRoomStmt         *sql.Stmt
	getAgentStmt           *sql.Stmt
	getRoomStmt            *sql.Stmt
	getTotalUsageStmt      *sql.Stmt
	listAgentsStmt         *sql.Stmt
	listMessagesByRoomStmt *sql.Stmt
	listRoomsStmt          *sql.Stmt
	listUsageLogsStmt      *sql.Stmt
	logUsageStmt           *sql.Stmt
	updateAgentStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createAgentStmt:        q.createAgentStmt,
		createMessageStmt:      q.createMessageStmt,
		createRoomStmt:         q.createRoomStmt,
		deleteAgentStmt:        q.deleteAgentStmt,
		deleteRoomStmt:         q.deleteRoomStmt,
		getAgentStmt:           q.getAgentStmt,
		getRoomStmt:            q.getRoomStmt,
		getTotalUsageStmt:      q.getTotalUsageStmt,
		listAgentsStmt:         q.listAgentsStmt,
		listMessagesByRoomStmt: q.listMessagesByRoomStmt,
		listRoomsStmt:          q.listRoomsStmt,
		listUsageLogsStmt:      q.listUsageLogsStmt,
		logUsageStmt:           q.logUsageStmt,
		updateAgentStmt:        q.updateAgentStmt,
	}
}
