// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package db

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, title, filename
) VALUES (
    ?, ?, ?
)
RETURNING id, title, filename, created_at, updated_at
`

type CreateDocumentParams struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Filename string `json:"filename"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.queryRow(ctx, q.createDocumentStmt, createDocument, arg.ID, arg.Title, arg.Filename)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentChunk = `-- name: CreateDocumentChunk :one
INSERT INTO document_chunks (
    id, document_id, content, chunk_index
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, document_id, content, chunk_index, created_at
`

type CreateDocumentChunkParams struct {
	ID         string `json:"id"`
	DocumentID string `json:"document_id"`
	Content    string `json:"content"`
	ChunkIndex int64  `json:"chunk_index"`
}

func (q *Queries) CreateDocumentChunk(ctx context.Context, arg CreateDocumentChunkParams) (DocumentChunk, error) {
	row := q.queryRow(ctx, q.createDocumentChunkStmt, createDocumentChunk,
		arg.ID,
		arg.DocumentID,
		arg.Content,
		arg.ChunkIndex,
	)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.ChunkIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDocumentStmt, deleteDocument, id)
	return err
}

const getChunk = `-- name: GetChunk :one
SELECT id, document_id, content, chunk_index, created_at FROM document_chunks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetChunk(ctx context.Context, id string) (DocumentChunk, error) {
	row := q.queryRow(ctx, q.getChunkStmt, getChunk, id)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.ChunkIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, filename, created_at, updated_at FROM documents
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.queryRow(ctx, q.getDocumentStmt, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChunksByDocument = `-- name: ListChunksByDocument :many
SELECT id, document_id, content, chunk_index, created_at FROM document_chunks
WHERE document_id = ?
ORDER BY chunk_index ASC
`

func (q *Queries) ListChunksByDocument(ctx context.Context, documentID string) ([]DocumentChunk, error) {
	rows, err := q.query(ctx, q.listChunksByDocumentStmt, listChunksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentChunk{}
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.ChunkIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, filename, created_at, updated_at FROM documents
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.query(ctx, q.listDocumentsStmt, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
