// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, room_id, agent_id, role, content, tokens_used
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, room_id, agent_id, role, content, tokens_used, created_at
`

type CreateMessageParams struct {
	ID         string         `json:"id"`
	RoomID     string         `json:"room_id"`
	AgentID    sql.NullString `json:"agent_id"`
	Role       string         `json:"role"`
	Content    string         `json:"content"`
	TokensUsed sql.NullInt64  `json:"tokens_used"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.RoomID,
		arg.AgentID,
		arg.Role,
		arg.Content,
		arg.TokensUsed,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AgentID,
		&i.Role,
		&i.Content,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT id, room_id, agent_id, role, content, tokens_used, created_at FROM messages
WHERE room_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMessagesByRoom(ctx context.Context, roomID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesByRoomStmt, listMessagesByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AgentID,
			&i.Role,
			&i.Content,
			&i.TokensUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
