// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Agent struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Model     string         `json:"model"`
	Provider  string         `json:"provider"`
	Persona   sql.NullString `json:"persona"`
	ApiKeyRef sql.NullString `json:"api_key_ref"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Document struct {
	ID        string       `json:"id"`
	Title     string       `json:"title"`
	Filename  string       `json:"filename"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type DocumentChunk struct {
	ID         string       `json:"id"`
	DocumentID string       `json:"document_id"`
	Content    string       `json:"content"`
	ChunkIndex int64        `json:"chunk_index"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Message struct {
	ID         string         `json:"id"`
	RoomID     string         `json:"room_id"`
	AgentID    sql.NullString `json:"agent_id"`
	Role       string         `json:"role"`
	Content    string         `json:"content"`
	TokensUsed sql.NullInt64  `json:"tokens_used"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Room struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Goal      sql.NullString `json:"goal"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type UsageLog struct {
	ID               int64           `json:"id"`
	Provider         string          `json:"provider"`
	Model            string          `json:"model"`
	PromptTokens     int64           `json:"prompt_tokens"`
	CompletionTokens int64           `json:"completion_tokens"`
	TotalTokens      int64           `json:"total_tokens"`
	LatencyMs        int64           `json:"latency_ms"`
	Cost             sql.NullFloat64 `json:"cost"`
	Timestamp        sql.NullTime    `json:"timestamp"`
}
