// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package db

import (
	"context"
	"database/sql"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    id, title, goal
) VALUES (
    ?, ?, ?
)
RETURNING id, title, goal, created_at, updated_at
`

type CreateRoomParams struct {
	ID    string         `json:"id"`
	Title string         `json:"title"`
	Goal  sql.NullString `json:"goal"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.queryRow(ctx, q.createRoomStmt, createRoom, arg.ID, arg.Title, arg.Goal)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Goal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteRoomStmt, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, title, goal, created_at, updated_at FROM rooms
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id string) (Room, error) {
	row := q.queryRow(ctx, q.getRoomStmt, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Goal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, title, goal, created_at, updated_at FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.query(ctx, q.listRoomsStmt, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Goal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
