// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usage.sql

package db

import (
	"context"
	"database/sql"
)

const getTotalUsage = `-- name: GetTotalUsage :one
SELECT
    COALESCE(SUM(total_tokens), 0) as total_tokens,
    COALESCE(SUM(cost), 0.0) as total_cost,
    COUNT(*) as total_requests
FROM usage_log
`

type GetTotalUsageRow struct {
	TotalTokens   interface{} `json:"total_tokens"`
	TotalCost     interface{} `json:"total_cost"`
	TotalRequests int64       `json:"total_requests"`
}

func (q *Queries) GetTotalUsage(ctx context.Context) (GetTotalUsageRow, error) {
	row := q.queryRow(ctx, q.getTotalUsageStmt, getTotalUsage)
	var i GetTotalUsageRow
	err := row.Scan(&i.TotalTokens, &i.TotalCost, &i.TotalRequests)
	return i, err
}

const listUsageLogs = `-- name: ListUsageLogs :many
SELECT id, provider, model, prompt_tokens, completion_tokens, total_tokens, latency_ms, cost, timestamp FROM usage_log
ORDER BY timestamp DESC, id DESC
LIMIT ? OFFSET ?
`

type ListUsageLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsageLogs(ctx context.Context, arg ListUsageLogsParams) ([]UsageLog, error) {
	rows, err := q.query(ctx, q.listUsageLogsStmt, listUsageLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageLog{}
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.Cost,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logUsage = `-- name: LogUsage :one
INSERT INTO usage_log (
    provider, model, prompt_tokens, completion_tokens, total_tokens, latency_ms, cost
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, provider, model, prompt_tokens, completion_tokens, total_tokens, latency_ms, cost, timestamp
`

type LogUsageParams struct {
	Provider         string          `json:"provider"`
	Model            string          `json:"model"`
	PromptTokens     int64           `json:"prompt_tokens"`
	CompletionTokens int64           `json:"completion_tokens"`
	TotalTokens      int64           `json:"total_tokens"`
	LatencyMs        int64           `json:"latency_ms"`
	Cost             sql.NullFloat64 `json:"cost"`
}

func (q *Queries) LogUsage(ctx context.Context, arg LogUsageParams) (UsageLog, error) {
	row := q.queryRow(ctx, q.logUsageStmt, logUsage,
		arg.Provider,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.Cost,
	)
	var i UsageLog
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.LatencyMs,
		&i.Cost,
		&i.Timestamp,
	)
	return i, err
}
